import random

DONE_WELL = [
    "Consistently reliable and can be counted on to deliver.",
    "Demonstrates strong ownership from start to finish.",
    "Communicates clearly and professionally with all stakeholders.",
    "Follows through on commitments without reminders.",
    "Plans work thoughtfully and executes to plan.",
    "Adapts quickly to changing priorities.",
    "Proactively identifies risks and flags them early.",
    "Collaborates effectively across teams and functions.",
    "Brings a calm, solutions-oriented mindset.",
    "Offers constructive input during discussions.",
    "Keeps stakeholders informed with timely updates.",
    "Shows strong attention to detail.",
    "Manages time well and meets deadlines.",
    "Asks insightful questions to clarify requirements.",
    "Produces high-quality, thorough deliverables.",
    "Documents decisions and context clearly.",
    "Is receptive to feedback and acts on it.",
    "Builds trust through consistent, transparent behavior.",
    "Handles ambiguity with steady judgment.",
    "Prioritizes effectively to focus on what matters.",
    "Demonstrates strong problem-solving skills.",
    "Thinks ahead and anticipates next steps.",
    "Takes initiative without waiting to be asked.",
    "Navigates blockers efficiently.",
    "Maintains a positive, can-do attitude.",
    "Shares knowledge generously with others.",
    "Listens actively and with empathy.",
    "Keeps meetings efficient and outcome-focused.",
    "Aligns work to business goals and outcomes.",
    "Balances speed with quality appropriately.",
    "Demonstrates professional integrity.",
    "Is dependable in high-pressure situations.",
    "Simplifies complex topics for wider audiences.",
    "Brings data to support recommendations.",
    "Facilitates productive discussions.",
    "Shows strong stakeholder management.",
    "Demonstrates continuous learning and growth.",
    "Provides clear action items and owners.",
    "Handles feedback with professionalism.",
    "Escalates issues responsibly when needed.",
    "Manages expectations realistically.",
    "Delivers incremental value iteratively.",
    "Keeps a customer-centric perspective.",
    "Demonstrates sound judgment in trade-offs.",
    "Stays organized and methodical.",
    "Contributes to a supportive team culture.",
    "Is responsive and easy to work with.",
    "Follows through on post-meeting actions.",
    "Ensures dependencies are clearly understood.",
    "Brings clarity to ambiguous requirements.",
    "Upholds high standards for accuracy.",
    "Proactively unblocks others.",
    "Demonstrates accountability for outcomes.",
    "Communicates succinctly without losing substance.",
    "Encourages inclusive participation in meetings.",
    "Prepares thoroughly ahead of discussions.",
    "Keeps documentation current and accessible.",
    "Aligns stakeholders around a clear plan.",
    "Manages scope thoughtfully to avoid churn.",
    "Demonstrates resilience when faced with setbacks.",
    "Raises thoughtful alternatives and options.",
    "Keeps workstreams aligned to timelines.",
    "Surfaces key risks with mitigation ideas.",
    "Partners well with adjacent teams.",
    "Brings constructive energy to the team.",
    "Follows best practices and standards.",
    "Stays focused on measurable outcomes.",
    "Maintains confidentiality and discretion.",
    "Clarifies roles and responsibilities early.",
    "Balances individual work and team goals.",
    "Organizes information logically for easy consumption.",
    "Creates clear, action-oriented summaries.",
    "Contributes to process improvements.",
    "Demonstrates consistency in quality over time.",
    "Keeps scope, schedule, and quality in balance.",
    "Encourages healthy debate and alignment.",
    "Handles handoffs cleanly and professionally.",
    "Is proactive about removing blockers.",
    "Maintains strong situational awareness.",
    "Drives clarity on success criteria.",
    "Fosters strong working relationships.",
    "Keeps deliverables aligned with requirements.",
    "Makes thoughtful, timely decisions.",
    "Communicates risks and impacts early.",
    "Offers help to teammates when bandwidth allows.",
    "Brings structure to complex work.",
    "Captures and shares lessons learned.",
    "Ensures stakeholders are prepared before milestones.",
    "Maintains high bar for craftsmanship.",
    "Uses feedback loops to refine outputs.",
    "Keeps discussions grounded in facts.",
    "Demonstrates reliability during tight timelines.",
    "Ensures alignment before execution.",
    "Is mindful of downstream impacts.",
    "Provides clear rationale behind choices.",
    "Shows strong follow-through on details.",
    "Keeps artifacts tidy and versioned.",
    "Encourages pragmatic, right-sized solutions.",
    "Communicates with empathy and respect.",
    "Consistently adds value beyond the immediate task."
]

CAN_IMPROVE = [
    "Could voice perspectives earlier to ensure your solid instincts guide direction.",
    "Consider projecting confidence slightly more to match your evident capability.",
    "May share a concise takeaway to amplify your already clear thinking.",
    "Could state a preferred option upfront; your judgment is usually well-founded.",
    "Consider summarizing decisions briefly to extend your influence beyond meetings.",
    "Might challenge assumptions gently; your questions often raise valuable angles.",
    "Could volunteer a next step; your suggestions tend to unblock progress.",
    "Consider delegating selectively to maximize your strengths on high-impact work.",
    "May publish brief notes; your clarity translates well into written form.",
    "Could signal trade-offs sooner; your balanced perspective accelerates alignment.",
    "Consider framing recommendations as headlines; your points merit emphasis.",
    "May ask one early clarifying question to spotlight your systems thinking.",
    "Could surface risks sooner; your mitigation ideas are usually practical.",
    "Consider sharing drafts a bit earlier; your work benefits from early visibility.",
    "Might compress explanations slightly; your insights are strong and persuasive.",
    "Could narrate brief reasoning; your logic reassures and guides decisions.",
    "Consider naming a simple next step; your direction-setting is already trusted.",
    "May designate owners succinctly; your leadership influence then travels further.",
    "Could simplify visuals slightly; your message is compelling on its own.",
    "Consider publishing short notes afterward; your clarity helps others move confidently.",
    "Might structure points into three bullets; your arguments become even crisper.",
    "Could restate the key point once; your emphasis reinforces alignment.",
    "Consider offering one recommended path first; your rationale then lands cleanly.",
    "Might use slightly stronger openers; your expertise warrants confident framing.",
    "Could outline scope briefly; your focus already drives effective execution."
]

def main():
    done = random.sample(DONE_WELL, 2)
    improve = random.choice(CAN_IMPROVE)
    print("Done Well:")
    print(f" - {done[0]}")
    print(f" - {done[1]}")
    print("\nCan Be Improved:")
    print(f" - {improve}")

if __name__ == "__main__":
    main()
